import express from "express";
import { protect } from "../../../middlewares/authMiddleware.js";
import { checkoutVersion, createCategory, createIdentifier, deleteCategory, deleteIdentifier, deleteVersion, getOverview, listCategories, listIdentifiers, listVersions, updateCategory, updateIdentifier, updateTransaction, updateTransactionCategory, uploadTransactions } from "../controllers/expenseAuditController.js";

const router = express.Router();
router.use(protect);
router.get("/identifiers/:companyId", listIdentifiers);
router.post("/identifiers", createIdentifier);
router.put("/identifiers/:id", updateIdentifier);
router.delete("/identifiers/:id", deleteIdentifier);
router.get("/categories/:companyId", listCategories);
router.post("/categories", createCategory);
router.put("/categories/:id", updateCategory);
router.delete("/categories/:id", deleteCategory);
router.patch("/transactions/:id/category", updateTransactionCategory);
router.patch("/transactions/:id", updateTransaction);
router.post("/upload", uploadTransactions);
router.get("/versions/:companyId/:financialYearEnding", listVersions);
router.post("/versions/:companyId/:financialYearEnding/checkout/:versionId", checkoutVersion);
router.delete("/versions/:companyId/:financialYearEnding/:versionId", deleteVersion);
router.get("/overview/:companyId", getOverview);
export default router;
